"""Repository layer for products.

This layer handles all database operations for products.
"""

from decimal import Decimal
from typing import Optional, List
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from db.models import Product


class ProductRepository:
    """Repository for product database operations."""
    
    def __init__(self, session: Session):
        """Initialize the repository with a database session.
        
        Args:
            session: SQLAlchemy session for database operations
        """
        self.session = session
    
    def create(
        self,
        tenant_id: str,
        name: str,
        sale_price: Decimal,
        is_active: bool = True,
        product_id: Optional[str] = None,
        recipe_id: Optional[str] = None
    ) -> Product:
        """Create a new product record.
        
        Args:
            tenant_id: ID of the tenant
            name: Name of the product
            sale_price: Selling price
            is_active: Whether product is active (defaults to True)
            product_id: Optional ID (if not provided, should be generated by service)
            recipe_id: Optional recipe ID for recipe-based costing
            
        Returns:
            Created Product instance
            
        Raises:
            IntegrityError: If database constraints are violated
        """
        product = Product(
            id=product_id,
            tenant_id=tenant_id,
            name=name,
            sale_price=sale_price,
            is_active=is_active,
            recipe_id=recipe_id
        )
        self.session.add(product)
        self.session.flush()  # Flush to get the ID without committing
        return product
    
    def get_by_id(self, tenant_id: str, product_id: str) -> Optional[Product]:
        """Get a product by ID, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            product_id: ID of the product
            
        Returns:
            Product instance or None if not found
        """
        return self.session.query(Product).filter(
            Product.id == product_id,
            Product.tenant_id == tenant_id
        ).first()
    
    def list_by_tenant(
        self,
        tenant_id: str,
        skip: int = 0,
        limit: int = 100
    ) -> List[Product]:
        """List products for a tenant with pagination.
        
        Args:
            tenant_id: ID of the tenant
            skip: Number of records to skip
            limit: Maximum number of records to return
            
        Returns:
            List of Product instances
        """
        return self.session.query(Product).filter(
            Product.tenant_id == tenant_id
        ).offset(skip).limit(limit).all()
    
    def update(
        self,
        tenant_id: str,
        product_id: str,
        **updates
    ) -> Optional[Product]:
        """Update a product record, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            product_id: ID of the product
            **updates: Fields to update
            
        Returns:
            Updated Product instance or None if not found
        """
        product = self.get_by_id(tenant_id, product_id)
        if not product:
            return None
        
        # Update allowed fields
        allowed_fields = {'name', 'sale_price', 'is_active', 'recipe_id'}
        for field, value in updates.items():
            if field in allowed_fields and value is not None:
                setattr(product, field, value)
        
        self.session.flush()
        return product
    
    def delete(self, tenant_id: str, product_id: str) -> bool:
        """Delete a product record, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            product_id: ID of the product
            
        Returns:
            True if deleted, False if not found
        """
        product = self.get_by_id(tenant_id, product_id)
        if not product:
            return False
        
        self.session.delete(product)
        self.session.flush()
        return True
