"""Repository layer for raw materials.

This layer handles all database operations for raw materials.
"""

from decimal import Decimal
from typing import Optional, List
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from db.models import RawMaterial


class RawMaterialRepository:
    """Repository for raw material database operations."""
    
    def __init__(self, session: Session):
        """Initialize the repository with a database session.
        
        Args:
            session: SQLAlchemy session for database operations
        """
        self.session = session
    
    def create(
        self,
        tenant_id: str,
        name: str,
        unit_of_measurement: str,
        cost_per_unit: Decimal,
        supplier: Optional[str] = None,
        raw_material_id: Optional[str] = None
    ) -> RawMaterial:
        """Create a new raw material record.
        
        Args:
            tenant_id: ID of the tenant
            name: Name of the raw material
            unit_of_measurement: Unit type (kg, g, L, etc.)
            cost_per_unit: Cost per unit
            supplier: Optional supplier name
            raw_material_id: Optional ID (if not provided, should be generated by service)
            
        Returns:
            Created RawMaterial instance
            
        Raises:
            IntegrityError: If database constraints are violated
        """
        raw_material = RawMaterial(
            id=raw_material_id,
            tenant_id=tenant_id,
            name=name,
            unit_of_measurement=unit_of_measurement,
            cost_per_unit=cost_per_unit,
            supplier=supplier,
            current_stock=Decimal("0")
        )
        self.session.add(raw_material)
        self.session.flush()  # Flush to get the ID without committing
        return raw_material
    
    def get_by_id(self, tenant_id: str, raw_material_id: str) -> Optional[RawMaterial]:
        """Get a raw material by ID, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            
        Returns:
            RawMaterial instance or None if not found
        """
        return self.session.query(RawMaterial).filter(
            RawMaterial.id == raw_material_id,
            RawMaterial.tenant_id == tenant_id
        ).first()
    
    def list_by_tenant(
        self,
        tenant_id: str,
        skip: int = 0,
        limit: int = 100
    ) -> List[RawMaterial]:
        """List raw materials for a tenant with pagination.
        
        Args:
            tenant_id: ID of the tenant
            skip: Number of records to skip
            limit: Maximum number of records to return
            
        Returns:
            List of RawMaterial instances
        """
        return self.session.query(RawMaterial).filter(
            RawMaterial.tenant_id == tenant_id
        ).offset(skip).limit(limit).all()
    
    def update(
        self,
        tenant_id: str,
        raw_material_id: str,
        **updates
    ) -> Optional[RawMaterial]:
        """Update a raw material record, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            **updates: Fields to update
            
        Returns:
            Updated RawMaterial instance or None if not found
        """
        raw_material = self.get_by_id(tenant_id, raw_material_id)
        if not raw_material:
            return None
        
        # Update allowed fields
        allowed_fields = {'name', 'unit_of_measurement', 'cost_per_unit', 'supplier', 'current_stock'}
        for field, value in updates.items():
            if field in allowed_fields and value is not None:
                setattr(raw_material, field, value)
        
        self.session.flush()
        return raw_material
    
    def delete(self, tenant_id: str, raw_material_id: str) -> bool:
        """Delete a raw material record, enforcing tenant isolation.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            
        Returns:
            True if deleted, False if not found
        """
        raw_material = self.get_by_id(tenant_id, raw_material_id)
        if not raw_material:
            return False
        
        self.session.delete(raw_material)
        self.session.flush()
        return True
    
    def add_stock(self, tenant_id: str, raw_material_id: str, quantity: Decimal) -> Optional[RawMaterial]:
        """Add stock to a raw material.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            quantity: Quantity to add (positive number)
            
        Returns:
            Updated RawMaterial instance or None if not found
        """
        raw_material = self.get_by_id(tenant_id, raw_material_id)
        if not raw_material:
            return None
        
        raw_material.current_stock += quantity
        self.session.flush()
        return raw_material
    
    def remove_stock(self, tenant_id: str, raw_material_id: str, quantity: Decimal) -> Optional[RawMaterial]:
        """Remove stock from a raw material with validation.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            quantity: Quantity to remove (positive number)
            
        Returns:
            Updated RawMaterial instance or None if not found
            
        Raises:
            ValueError: If stock would go negative
        """
        raw_material = self.get_by_id(tenant_id, raw_material_id)
        if not raw_material:
            return None
        
        if raw_material.current_stock < quantity:
            raise ValueError(f"Insufficient stock. Current: {raw_material.current_stock}, Requested: {quantity}")
        
        raw_material.current_stock -= quantity
        self.session.flush()
        return raw_material
    
    def get_stock(self, tenant_id: str, raw_material_id: str) -> Optional[Decimal]:
        """Get the current stock level of a raw material.
        
        Args:
            tenant_id: ID of the tenant
            raw_material_id: ID of the raw material
            
        Returns:
            Current stock level or None if not found
        """
        raw_material = self.get_by_id(tenant_id, raw_material_id)
        if not raw_material:
            return None
        
        return raw_material.current_stock
